" ** Código melhorado ** "
print('Ola usuario! Seja bem vindo!')
print('Vamos começar inserindo dois numeros...')
num1 = int(input('Digite o primeiro numero:'))
num2 = int(input('Digite o segundo numero:'))
print ("A Soma destes numeros são: ", num1 + num2)
print('Vamos praticar a Multiplicação:')
num5 = int(input('Digite o primeiro numero:'))
num6 = int(input('Digite o segundo numero:'))
print ("A Multiplicacao é: ", num5 * num6)
print('Vamos praticar a Subtração:')
num3 = int(input('Digite o primeiro numero:'))
num4 = int(input('Digite o segundo numero:'))
print ("Subtracao é ", num4 - num3)

